# Generated by Django 4.0.6 on 2022-08-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='filmes_visto',
            new_name='filmes_vistos',
        ),
    ]
